# -*- coding: utf-8 -*-
"""homework10_5210.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10i_K11uxxBEXPIPVK_7bdAlk9vKvxQlA

# Exploring GPT

In this homework assignment we will walk you through how to use GPT-3.5, a large pre-trained neural language model developed by OpenAI.  

You will learn about the following topics:
* Prompts and completions.  You should observe that the the quality of the text generated is high quality, but not necessarially factually accurate.
* Probabilities.  You'll learn how to inspect probabilities assigned to words in the model's output.
* Few shot learning.  We'll see an example of few-shot learning with a small handful of examples.
* Zero shot learning.  We will explore the zero-shot capabilities of pre-trained LMs.  You'll design zero-shot prompts for
1. summarization
2. question-answering
3. simplification
4. translation
* How to fine tune a model.  You will learn how to fine-tune GPT-3.5 to take a Wikipedia infobox as input and generate the text of a biography as its ouput.  You'll then write your own code to do the reverse task – given a biography, extract the  attributes and values in the style of a Wikipedia infobox.

Before you get started, please [sign up for OpenAI.](https://platform.openai.com/signup). In order to complete this assignment, you will need to provide a payment method to OpenAI. You can load in a finite amount of credit, 5 dollars at a time. Be aware that each token generated—through the Playground or otherwise—will deplete your credit slightly. It is possible to complete this assignment with a very small amount of credit—less than $2 was my cost, but in order to do so, you must refrain from repeatedly calling the API. This goes doubly so for starting fine-tune jobs.



# Prompt Completion

As a warm-up we'll have you play with [the OpenAI Playground](https://platform.openai.com/playground?mode=complete).  Try inputting this prompt:

> One of my favorite professors at the University of Pennsylvania is

And the click the "Submit" button to generate a completion.

Copy and paste the text below (including your prompt).

You might notice that the output sometimes ends mid-sentence.  GPT-3.5 will generate text until it either generates a special "stop sequence" token `<|endoftext|>`, or it outputs the number of tokens specified by the `maximum length` variable.
You can press Submit again to have it continue generation, or you can increase the max length variable in the sliderbar on the right.
"""

favorite_professor_completion_1 = """
One of my favorite professors at the University of Pennsylvania is  Dr. James Weiner. He is a professor in the psychology department and teaches courses on the topics of cognitive psychology and attention.

What sets Dr. Weiner apart from other professors is his passion for the subject matter and his dedication to his students. In every class, he ensures that students understand the material by providing real-world examples and engaging class discussions. He encourages critical thinking and challenges students to push themselves academically.

Dr. Weiner also goes above and beyond to support his students. He is always available for office hours and is happy to discuss any questions or concerns students may have. He even provides personalized feedback on assignments and exams to help students improve their understanding of the material.

In addition, Dr. Weiner's teaching style is dynamic and engaging. He incorporates various teaching methods, such as demonstrations, group activities, and videos, to keep the class interesting and interactive. His lectures are organized and informative, making it easy for students to follow along and retain the information.

One of the most impressive things about Dr. Weiner is his research and publication record. He is an expert in the field of cognitive psychology and has published numerous articles and books on the subject. He brings his wealth of knowledge and experience into the classroom, making the material both interesting and relevant.

I have had the pleasure of taking multiple courses with Dr. Weiner, and each semester I have deepened my understanding and appreciation for cognitive psychology. His courses have been some of the most challenging and rewarding classes I have taken at Penn, and I attribute much of that to his exceptional teaching.

Overall, Dr. James Weiner is a phenomenal professor who truly cares about his students' learning and growth. His passion for the subject and dedication to his students make him a standout educator at the University of Pennsylvania. I am grateful for the opportunity to have learned from him, and I highly recommend his courses to anyone interested in cognition and attention.
"""

"""GPT generates fluent text, but it is not always grounded in fact.  Let's do a Google search for the person that GPT generated as your favorite professor and check:
* Are they actually a professor?
* Where do they work?
"""

# Extract the professor's name
professor_name_1 = "Dr. James Weiner"

# Do a Google search and answer these questions
actually_a_professor_1 = False

# Insitituion where they work
instituion_1 = "Not a real person. Closest person is Dr. David B. Weiner who works at Perelman School of Medicine"

"""When it generates its completions, GPT generates each new word/token according to its probability distribution.  It draws each word at random in proportion to its propability.  That randomness means that it can generate different completions. You can re-generate and get different completions each time.

Generate another 4 completions for the professor prompt:

> One of my favorite professors at the University of Pennsylvania is

and do Google searches for them.

*Tip: You can generate another response with the Regenerate button to the right of the Submit button.  The Regenerate button has a recycle symbol on it.*
"""

favorite_professor_completion_2 = """
One of my favorite professors at the University of Pennsylvania is Dr. Rochelle Terman, who teaches in the Political Science department. Dr. Terman is not only an incredibly knowledgeable and engaging professor, but also plays an active role in promoting social justice and equality on campus and in her research. She is a passionate advocate for women's rights and LGBTQ+ rights, and incorporates these topics into her lectures and class discussions.

What stands out about Dr. Terman's teaching style is her ability to blend academic theory with real-world examples and current events. She challenges her students to critically analyze complex issues and encourages them to form their own opinions through class debates and activities. She also makes sure to create a welcoming and inclusive environment for all students, regardless of their background or beliefs.

I have taken multiple classes with Dr. Terman and have always been impressed by her dedication and support for her students. She goes above and beyond to make sure her students understand the material and offers additional resources for those who are struggling. Even outside of class, she is always willing to meet with students and offer guidance and advice.

In addition to her teaching, Dr. Terman is also an accomplished researcher and her work on gender and politics has been published in top academic journals. She is a role model for young women interested in pursuing a career in political science and her dedication to advancing social justice is truly inspiring.

Overall, Dr. Rochelle Terman is an exceptional professor who not only imparts valuable knowledge to her students but also serves as a mentor and advocate for social change. She has had a significant impact on my academic and personal development, and I am grateful to have had the opportunity to learn from her.
"""

favorite_professor_completion_3 = """
One of my favorite professors at the University of Pennsylvania is also one of the most absolutely terrifying teachers I’ve ever taken. He is truly passionate about his students learning, and insists that someone who really wants to learn—an ever-shrinking group—is willing to bear the pain of thinking about difficult, complicated, contradictory ideas. He seems to think that a university’s primary responsibility is to offer a place that gives them the chance to do so.

Who cares if a subject is intimidating? In my experience, inspirational professors—not online classes, not online content, not Khan Academy— are the instigators and the catalysts that make brave teaching and learning happen. We need to create more than lectures, more than explanations and simple knowledge paths, more than bland formulations of what we think students want or should learn.

Such a statement is, of course, a provocation. Click ProvocationNano for a pdf copy of this blog barely disguised as a peer-reviewed article.
"""

favorite_professor_completion_4 = """
One of my favorite professors at the University of Pennsylvania is doing some really interesting and groundbreaking work on visual cognition, and I wanted to share her recent TED Talk.

Dr. Isabel Gauthier's TED Talk, "How Your Brain Determines What You See," delves into the complexities of how our brains process and interpret visual information. She explains how we often take for granted the incredible power and efficiency of our visual system, but also highlights the challenges and limitations it faces when trying to make sense of the world.

Using examples from her research, Dr. Gauthier demonstrates how our brains are able to recognize patterns and objects, make fine distinctions between similar things, and even create new categories based on our prior knowledge and experience.

As someone who has always been fascinated by the workings of the brain, I found this talk to be both enlightening and thought-provoking. It's incredible to think about the amazing feats our brains are capable of, especially when it comes to vision and perception.

I highly recommend watching this TED Talk to gain a deeper understanding and appreciation for the incredible complexity of our visual cognition. Trust me, you won't be disappointed!
"""

favorite_professor_completion_5 = """
One of my favorite professors at the University of Pennsylvania is Dr. Colin MacCabe. Dr. MacCabe is perhaps best known as a scholar of MARXISM, FEMINISM, and French film. He has written and co-edited numerous books and is a professor at both UPenn and the University of Exeter.



Although his expertise covers a wide range of topics, what makes Dr. MacCabe so impactful to his students is his passion for teaching and his enthusiasm for critical thinking. In his lectures, he effortlessly connects complex theories and ideas to everyday life, making the material relevant and engaging. He encourages his students to think critically about the world around them and to never accept something as true without questioning it first.

Dr. MacCabe also has a genuine interest in his students' personal and academic growth. He often takes the time to meet with students outside of class to discuss their ideas and offer guidance. As a graduate student, I have had the pleasure of seeing Dr. MacCabe in action as a mentor to other students in our department, always offering support and advice to help them succeed.

One of the most memorable experiences I had with Dr. MacCabe was in his seminar on Marxist theory. He challenged us to think beyond traditional interpretations of Marxist thought and encouraged us to apply these theories to contemporary issues. Through in-depth discussions and thought-provoking readings, he helped us understand the relevance of Marxism in today's society and the impact it can have in shaping social change.

Overall, Dr. MacCabe's dedication to his students, his expertise, and his ability to make challenging material accessible and engaging, make him one of the most revered and beloved professors at UPenn. He truly embodies the university's commitment to academic excellence and has left a lasting impact on the intellectual growth of his students.
"""

# Do a Google search for these professors

professor_name_2 = "Dr. Rochelle Terman"
actually_a_professor_2 = True
instituion_2 = "University of Chicago"

professor_name_3 = "No name"
actually_a_professor_3 = False
instituion_3 = "N/A"

professor_name_4 = "Dr. Isabel Gauthier's"
actually_a_professor_4 = True
instituion_4 = "Vanderbuilt University"

professor_name_5 = "Dr. Colin MacCabe"
actually_a_professor_5 = True
instituion_5 = "University of Pittsburg"

"""## Probabilities

Just like with the n-gram language models that we stuided earlier in the course, neural language models like GPT-3.5 assign probabilities to each token in a sequence.  

For example, if you input the previous prompt and select , the distribution over words to follow "Professor" might resemble this:
```
X = 27.80%
Jane = 23.01%
John = 7.89%
[ = 6.32%
L = 2.86%
Total: -2.54 logprob on 1 tokens
(67.88% probability covered in top 5 logits)
```

One critical observation about language models is that they often encode societal biases that appear in their data.  For instance, after the disovery that LM embeddings could be used to solve word analogy problems like "**man** is to **woman** as **king** is to ___" (the model predicts **queen**), researchers discovered that LMs had a surpisingly sexist answer to the analogy problem  "**man** is to **woman** as **computer programmer** is to ___" (the model predicts **homemaker**).  These kinds of biases are prevelant and pernicious.

Let's examine the most probable names that GPT assigns to different completions and analyze their gender.  We'll see if it associates different genders with different academic disciplines.  (You can also see this for different careers like *nurse*, *plumber*, or *school teacher*).

Please create dictionaries mapping GPT's predictions for the first names of professors in these departments
* Computer Science
* Gender Studies
* Physics
* Linguistics
* Bioengineering
Use the following prompt for each of the above departments and note the distribution of names & genders that GPT generates for each professor:
> My favorite class in the {deparment_name} Department was taught by Professor

**Note: you can also add a stop sequence of `.` to get the model to complete only a single sentence.**


"""

# Classify each name as male, female, partial word, or unknown
computer_science_genders = {
  "Joe" : "male",
  "John" : "male",
  "Nancy" : "female",
  "David" : "male",
  "Barbara" : "female",
}

gender_studies_genders = {
  "Smith" : "male",
  "Rodriguez" : "male",
  "Thompson" : "partial word",
  "Patel" : "male",
  "Nguyen" : "partial word",
}

physics_genders = {
  "Jones" : "female",
  "Patel" : "male",
  "Kim" : "partial word",
  "Chen" : "partial word",
  "Singh" : "unknown",
}

lingusitics_genders = {
  "Martinez" : "male",
  "Lee" : "male",
  "Smith" : "male",
  "Jane" : "female",
  "Garcia" : "partial word",
}

bioengineering_genders = {
  "Richard" : "male",
  "John" : "male",
  "Austin" : "male",
  "Johnson" : "male",
  "Hartmut" : "male",
}

"""The sample size is low, but you can take a moment to reflect: does the model seem to obviously associate different disciplines with professors of a specific gender?

# Few Shot Learning

One of the remarkable properties of large language models is a consequence of the fact that they have been trained on so much language data.  They encode that training data as background information that lets them learn new tasks and to generalize patterns using only a few examples.  This is called "Few shot learning".

Here is an example.  Imagine that we want to build a system that allows a student to say something they want to learn, and the system will recommend the subject for them to study.  Here are examples of inputs and outputs to our program:

```
how to program in Python - computer science
factors leading up to WW2 - history
branches of government - political science
Shakespeare's plays - English
cellular respiration - biology
respiratory disease - medical
how to sculpt - art
```

We can use these 7 examples (and probably fewer!) as a prompt to GPT-3.5, and it will perform few shot learning by figuring out what our pattern is, and being able to perform the task for new inputs.

Try pasting those examples into the Playground, and then listing out a few lessons (one by one) to see what is output.

```
cellular respiration
respiratory disease
how to play saxophone
autonomic system
how write a screenplay
perform in a play
stock market
planetary orbits
relativity
```

Fill in the dictionary below using the playground by replacing the TODOs with the model's predictions.
"""

few_shot_subject_classification_results = {
  "cellular respiration" : "biology",
  "respiratory disease" : "medical",
  "how to play saxophone" : "music",
  "autonomic system" : "neuroscience",
  "how write a screenplay" : "drama/theater",
  "perform in a play" : "film studies",
  "stock market" : "finance",
  "planetary orbits" : "astronomy",
  "relativity" : "physics",
}

"""## Using the API

Now let's take a look at how to call the OpenAI API from our code, so that we don't have to manually enter inputs into the Playground.  

If you click on the "View code" button on the playground, you'll see a sample of code for whatever prompt you have.  For example, here's the code that we have for our few-shot learning that generates a subject to study for a topic that someone is interested in:

```python
import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.Completion.create(
  model="text-davinci-002",
  prompt="how to program in Python - computer science\nfactors leading up to WW2 - history\nbranches of government - political science\nShakespeare's plays - English\ncellular respiration - biology\nrespiratory disease - medical\nhow to sculpt - art",
  temperature=0.7,
  max_tokens=256,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0
)
```
This is python code, so it'll be pretty easy for us to use this as a starting point and to modify it to create a function that we can call.


First, you'll need install the OpenAPI via pip.  You can use Unix commands in a colab notebook by prefixing them with an exclamation point. The example below uses a `%` prefix instead—this guarantees that the installation is done using the same Python version that your notebook is using. Change line 2 from `%pip...` to `!pip...` if you're running into trouble. (The `%%capture` command before that just surpresses the output of running the Unix command.  You can remove it if you want to see the progress of the command).

"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install openai

"""Next, you will enter your secret key for the OpenAI API. You can generate your OpenAI API key [here](https://platform.openai.com/api-keys).  

We will enter it as a password, so that the raw text of it doesn't get saved in your Python notebook. That would be bad in the case that you upload or share your notebook, because then other people could use your key and have you pay for their usage.
"""

from getpass import getpass
import openai
import os

print('Enter OpenAI API key:')
openai.api_key = getpass()

os.environ['OPENAI_API_KEY']=openai.api_key

"""Now let's write a function that takes a topic as input and then outputs a subject to study if you want to learn about that topic."""

import openai
import os
import time

def generate_subject_few_shot(topic):
  few_shot_prompt = """how to program in Python - computer science
factors leading up to WW2 - history
branches of government - political science
Shakespeare's plays - English
cellular respiration - biology
respiratory disease - medical
how to sculpt - art
"""

  # All GPT completions are generated by the chat model now. The chat model works best
  # when it's given a baseline instruction about how GPT should behave. We'll use this one.
  system_message = {"role" : "system", "content" : "You should recognize a pattern in the prompts and generate a completion based on that pattern."}

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user", "content" : few_shot_prompt + topic + " - "} # simulate a user prompt
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )
  # I recommend putting a short wait after each call,
  # since the rate limit for the platform is 60 requests/min.
  # (This increases to 3000 requests/min after you've been using the platform for 2 days).
  time.sleep(1)

  # the response from OpenAI's API is a JSON object that contains
  # the completion to your prompt plus some other information.  Here's how to access
  # just the text of the completion.
  return response.choices[0].message.content.strip()

topic = "cellular respiration"
generate_subject_few_shot(topic)

"""That's it!  That's an exampe of how to write a function call to the OpenAI API in order for it to output a subject for a topic.

Here is some information about the different arguments that we to the `openai.Completion.create` call:
 * `model` – OpenAI offers many different versions of their chat model. We'll use GPT3.5-turbo, which is functional without being [the most expensive to run](https://openai.com/api/pricing/).
 * `messages` - this is the set of messages that will instruct how the model should respond. The first message is a system prompt—an overall setting that specifies how the model should behave. In this case, the second message is the "training set" of examples followed by the last topic that we want to generate a subject for.
 * `temperature` - controls how much of the probability distribution the model will use when it is generating each token. 1.0 means that it samples from the complete probability distrubiton, 0.7 means that it drops the bottom 30% of the least likely tokens when it is sampling. 0.0 means that it will perform deterministically and always output the single most probable token for each context.
 * `top_p` - is an alternative way of controling the sampling.
 * `frequency_penalty` and `presence_penalty` are two ways of reduing the model from repeating the same words in one output.  You can set these to be >0 if you're seeing a lot of repetition in your output.
 * `max_tokens` is the maximum length in tokens that will be output by calling the function.  A token is a subword unit.  There are roughly 2 or 3 tokens per word on average.
 * `stop` is a list of stop sequences.  The model will stop generating output once it generates one of these strings, even if it hasn't reached the max token length. By default this is set to a special token `<|endoftext|>`.

You can read more about [the Chat Completion API call in the documentation](https://cookbook.openai.com/examples/how_to_format_inputs_to_chatgpt_models).

# Zero shot learning

In addition to few shot learning, GPT can sometimes also perform "zero shot learning" where instead of giving it several examples of what we want it to do, we can instead give it instructions of what we want it to do.

For example, for our topic - subject task we could give GPT the prompt

> Given a topic, output the subject that a student should study if they want to know more about that topic.

Then if we append
> cellular respiration -

GPT will output `biology`—or something similar. Since there is no training, you might have to accept slight variability in the output. `biology` and `biochemistry` are both reasonable outputs for the input `cellular respiration -`.

Try to adapt the `generate_subject_few_shot` function to do a zero-shot version.
"""

def generate_subject_zero_shot(topic):
  system_message = {
      "role" : "system",
      "content" : "You should recognize a pattern in the prompts and generate a completion based on that pattern."}

  direction = "Given a topic, output the subject that a student should study if they want to know more about that topic."

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user", "content" : direction + topic + " - "}
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )

  time.sleep(1)

  return response.choices[0].message.content.strip()


topic = "cellular respiration"
generate_subject_zero_shot(topic)

"""A very cool recent finding is that training procedure for LLMs can be changed to improve this instruction following behavior.  If LLMs are [trained to do multiple tasks through prompting](https://arxiv.org/abs/2110.08207), they better generalize to complete new tasks in a zero-shot fashion.

Try writing zero-shot prompts to do the following tasks:
1. Summarize a Wikipedia article.
2. Answer questions about an article.
3. Re-write an article so that it's suitable for a young child who is just learning how to read (age 8 or so).
4. Translate an article from Russian into English.

You should experiment with a few prompts in the playground to find a good prompt that seems to work well.
"""

def summarize(article_text):
  system_message = {
      "role" : "system",
      "content" : "You should recognize a pattern in the prompts and generate a completion based on that pattern."}

  direction = "Summarize the main ideas of the article text"

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user", "content" : direction + article_text + " - "}
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )

  time.sleep(1)

  summary = response.choices[0].message.content.strip()

  return summary

def answer_question(article_text, question):
  system_message = {
    "role" : "system",
    "content" : "You should recognize a pattern in the prompts and generate a completion based on that pattern."}

  direction = "Read through the article text and then answer the question based on the article"

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user", "content" : direction + article_text + question + " - "}
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )

  time.sleep(1)

  answer = response.choices[0].message.content.strip()
  return answer

def simplify(article_text):
  system_message = {
      "role" : "system",
      "content" : "You should recognize a pattern in the prompts and generate a completion based on that pattern."}

  direction = "Read through the given article and simply the text so the simplied article is readable by a young child around age 8 or so"

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user", "content" : direction + article_text + " - "}
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )

  time.sleep(1)

  simplified_article = response.choices[0].message.content.strip()
  return simplified_article

def translate(article_text, source_language, target_language):
  system_message = {
      "role" : "system",
      "content" : "You should recognize a pattern in the prompts and generate a completion based on that pattern."}

  direction = "Read through the given article in the given source_language and translate the article into the given target language"

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user",
           "content" : direction + article_text + source_language + target_language + " - "}
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )

  time.sleep(1)

  simplified_article = response.choices[0].message.content.strip()
  return simplified_article

"""Show your outputs in your prompts.  The colab notebook that you turn in should have these outputs for the TAs and professor to review."""

article_text = """
Haruhi Suzumiya (Japanese: 涼宮ハルヒ, Hepburn: Suzumiya Haruhi) is a Japanese light novel series written by Nagaru Tanigawa and illustrated by Noizi Ito. It was first published in 2003 by Kadokawa Shoten in Japan with the novel The Melancholy of Haruhi Suzumiya, and has since been followed by 11 additional novel volumes, an anime television series adaptation produced by Kyoto Animation, four manga series, an animated film, two original net animation series and several video games.

After the anime adaptation airing in 2006, publishing company Kadokawa Shoten received offers for licensing the novels and their adaptations.[3][4] The novels are licensed for English language release in the United States by Little, Brown and Company, for young readers by Yen Press and the anime adaptation was licensed for North American distribution by Kadokawa Pictures USA division which then sub-licensed production and distribution to Bandai Entertainment. The anime is currently licensed by Crunchyroll.

The anime series became an Internet phenomenon in Japan, Asia, and English-speaking countries. Over 2,000 clips of the series and user-created parodies and homages were posted to video sharing websites such as YouTube[88] and the Japanese video-sharing website Nico Nico Douga.

One particular homage is the recreation of the dance choreography in the ending animation of the theme song, "Hare Hare Yukai", which generated so much public interest that it was credited for establishing the cover dance genre on Nico Nico Douga and YouTube.[89] The popularity of these clips (and those of other popular Japanese series) led the Japanese Society for Rights of Authors, Composers and Publishers (JASRAC) to request that YouTube remove clips claimed to be under the copyright of their members.[90] Business journalist Tadashi Sudo attributed the anime series' success towards coming out during a time when the Internet streaming market was new and being able to take advantage of it.[89] An example described was how Nico Nico Douga was established around the same time the anime series debuted, and they were able to capitalize off each other's success.[89]

The popularity of the series made Aya Hirano one of the earliest examples of the "idol voice actor" crossover in the late 2000s.[91] Haruhi, Yuki, and Mikuru (voiced by Aya Hirano, Minori Chihara, and Yūko Gotō), along with Japanese drama actor Toma Ikuta, made their first Japanese ad appearance in promoting Lotte Acuo Gum in March 2010.[92][93]

The non-chronological broadcast order of the anime inspired a math problem: "What is the fewest number of Haruhi episodes that one would have to watch in order to see the original 14 episodes in every order possible?" In 2011, efforts to solve "The Haruhi Problem" on 4chan led to a proof of the lower bound for the minimal length of superpermutations, solving what had been an open math problem since 1993.[94]
"""

summarize(article_text)

article_text = """
Haruhi Suzumiya (Japanese: 涼宮ハルヒ, Hepburn: Suzumiya Haruhi) is a Japanese light novel series written by Nagaru Tanigawa and illustrated by Noizi Ito. It was first published in 2003 by Kadokawa Shoten in Japan with the novel The Melancholy of Haruhi Suzumiya, and has since been followed by 11 additional novel volumes, an anime television series adaptation produced by Kyoto Animation, four manga series, an animated film, two original net animation series and several video games.

After the anime adaptation airing in 2006, publishing company Kadokawa Shoten received offers for licensing the novels and their adaptations.[3][4] The novels are licensed for English language release in the United States by Little, Brown and Company, for young readers by Yen Press and the anime adaptation was licensed for North American distribution by Kadokawa Pictures USA division which then sub-licensed production and distribution to Bandai Entertainment. The anime is currently licensed by Crunchyroll.

The anime series became an Internet phenomenon in Japan, Asia, and English-speaking countries. Over 2,000 clips of the series and user-created parodies and homages were posted to video sharing websites such as YouTube[88] and the Japanese video-sharing website Nico Nico Douga.

One particular homage is the recreation of the dance choreography in the ending animation of the theme song, "Hare Hare Yukai", which generated so much public interest that it was credited for establishing the cover dance genre on Nico Nico Douga and YouTube.[89] The popularity of these clips (and those of other popular Japanese series) led the Japanese Society for Rights of Authors, Composers and Publishers (JASRAC) to request that YouTube remove clips claimed to be under the copyright of their members.[90] Business journalist Tadashi Sudo attributed the anime series' success towards coming out during a time when the Internet streaming market was new and being able to take advantage of it.[89] An example described was how Nico Nico Douga was established around the same time the anime series debuted, and they were able to capitalize off each other's success.[89]

The popularity of the series made Aya Hirano one of the earliest examples of the "idol voice actor" crossover in the late 2000s.[91] Haruhi, Yuki, and Mikuru (voiced by Aya Hirano, Minori Chihara, and Yūko Gotō), along with Japanese drama actor Toma Ikuta, made their first Japanese ad appearance in promoting Lotte Acuo Gum in March 2010.[92][93]

The non-chronological broadcast order of the anime inspired a math problem: "What is the fewest number of Haruhi episodes that one would have to watch in order to see the original 14 episodes in every order possible?" In 2011, efforts to solve "The Haruhi Problem" on 4chan led to a proof of the lower bound for the minimal length of superpermutations, solving what had been an open math problem since 1993.[94]
"""
questions = [
    "Who is the main character of topic in the article?",
    "Why was Haruhi Suzumiya culturally important?",
    "What are some of the major impacts that Haruhi Suzumiya have on related personnel?",
    "What problem did the watchers of the Haruhi Suzumiya face?",
    "What are the production companies involved in the animation of Haruhi Suzumiya",
]

for question in questions:
  answer = answer_question(article_text, question)
  print(question)
  print(answer)
  print('---')

article_text = """
Haruhi Suzumiya (Japanese: 涼宮ハルヒ, Hepburn: Suzumiya Haruhi) is a Japanese light novel series written by Nagaru Tanigawa and illustrated by Noizi Ito. It was first published in 2003 by Kadokawa Shoten in Japan with the novel The Melancholy of Haruhi Suzumiya, and has since been followed by 11 additional novel volumes, an anime television series adaptation produced by Kyoto Animation, four manga series, an animated film, two original net animation series and several video games.

After the anime adaptation airing in 2006, publishing company Kadokawa Shoten received offers for licensing the novels and their adaptations.[3][4] The novels are licensed for English language release in the United States by Little, Brown and Company, for young readers by Yen Press and the anime adaptation was licensed for North American distribution by Kadokawa Pictures USA division which then sub-licensed production and distribution to Bandai Entertainment. The anime is currently licensed by Crunchyroll.

The anime series became an Internet phenomenon in Japan, Asia, and English-speaking countries. Over 2,000 clips of the series and user-created parodies and homages were posted to video sharing websites such as YouTube[88] and the Japanese video-sharing website Nico Nico Douga.

One particular homage is the recreation of the dance choreography in the ending animation of the theme song, "Hare Hare Yukai", which generated so much public interest that it was credited for establishing the cover dance genre on Nico Nico Douga and YouTube.[89] The popularity of these clips (and those of other popular Japanese series) led the Japanese Society for Rights of Authors, Composers and Publishers (JASRAC) to request that YouTube remove clips claimed to be under the copyright of their members.[90] Business journalist Tadashi Sudo attributed the anime series' success towards coming out during a time when the Internet streaming market was new and being able to take advantage of it.[89] An example described was how Nico Nico Douga was established around the same time the anime series debuted, and they were able to capitalize off each other's success.[89]

The popularity of the series made Aya Hirano one of the earliest examples of the "idol voice actor" crossover in the late 2000s.[91] Haruhi, Yuki, and Mikuru (voiced by Aya Hirano, Minori Chihara, and Yūko Gotō), along with Japanese drama actor Toma Ikuta, made their first Japanese ad appearance in promoting Lotte Acuo Gum in March 2010.[92][93]

The non-chronological broadcast order of the anime inspired a math problem: "What is the fewest number of Haruhi episodes that one would have to watch in order to see the original 14 episodes in every order possible?" In 2011, efforts to solve "The Haruhi Problem" on 4chan led to a proof of the lower bound for the minimal length of superpermutations, solving what had been an open math problem since 1993.[94]
"""

simplify(article_text)

russian_article = """
Харухи Судзумия (яп. 涼宮ハルヒ Судзумия Харухи) — имя героини ранобэ, которое объединяет ряд посвящённых ей художественных произведений различного формата. Отдельные тома ранобэ выходили по одной под разными названиями вида «Suzumiya Haruhi no…» (яп. 涼宮ハルヒの… Судзумия Харухи но…), то есть, буквально: «что-либо Харухи Судзумии». Автор сюжета — Нагару Танигава, иллюстраций — Ито Нойдзи. До выхода в виде отдельного издания ранобэ о Харухи Судзумии публиковались в журнале The Sneaker издательства Kadokawa Shoten, которое отвечает за публикацию и ряда манга-адаптаций.

На основе ранобэ вышли манга и аниме-адаптации. С 5 июля 2006 года на сайте компании Lantis выходят передачи интернет-радио с участием сэйю трёх главных героинь аниме. Передачи называются «Радзиобангуми» (ラジオ番組), то есть «Радиопередача»[4].

Премьерный показ 14-серийного аниме-телесериала производства Kyoto Animation под названием «Меланхолия Харухи Судзумии» прошёл на телевидении Японии в 2006 году. Аниме охватывает первую и третью книги, а также фрагменты второй, пятой и шестой. Компанией «Реанимедиа» приобретена лицензия на данную аниме-адаптацию на территории России, Белоруссии, Украины, Казахстана и стран Балтии. DVD-издание с русским дубляжом поступило в продажу в середине лета 2008 года. 27 сентября 2010 года было объявлено о лицензировании второго сезона сериала и аниме-фильма «Исчезновение Харухи Судзумии»[2].

Публикация десятой книги неоднократно откладывалась. Премьерная трансляция второго сезона главной аниме-адаптации прошла в 2009 году в Японии — в рамках показа как старых, так и новых серий в хронологическом[5] порядке разворачивающихся в них событий (первая из новых серий показана 22 мая (по московскому времени — 21 мая) 2009[6]). Появление новых серий в эфире произошло без официальных объявлений и анонсов. Телепоказ первоначально был заявлен как простой повтор первого и единственного сезона[7][8].

26 апреля 2013 года в продажу поступил артбук Ито Нойдзи «Сто цветов Харухи» (яп. ハルヒ百花 Харухи хякка) с рассказом «Случайные числа» (яп. あてずっぽナンバーズ Атэдзуппа намба:дзу). В выпущенном 31 октября 2018 года журнале «The Sneaker LEGEND» был опубликован рассказ «Овертайм семи тайн» (яп. 七不思議オーバータイム Нанафусиги о:ба:таиму).

12-й том под названием «Интуиция Харухи Судзумии» (яп. 涼宮ハルヒの直観 Судзумия Харухи но тёккан) появился в продаже 25 ноября 2020 года, в него вошли рассказы «Случайные числа» и «Овертайм семи тайн», опубликованные ранее, и новый рассказ «Вызов Цуруи»[9].
"""

source_language = "Russian"
target_language = "English"
translate(russian_article, source_language, target_language)

"""## TODO - Pick your own task

For this section you should pick some task that you'd like to have GPT do.  Add a description and code to your notebook here.  You should:
1. Write a short description of what task you tried, why you were interested in it.
2. Give some code so that we can reproduce what you did via an Open API call.  You should include output of your code in the Python Notebook that you turned in.
3. Write a short qualitative analysis of whether or not GPT did the task well.

TODO - your task description

1. Description of Task
Recent animes have not been my favorites to watch so I think this could be a good use of having GPT give me recommendations of animes so I don't need to go look for them. To do so, I will first give GPT the list of top 10 animes that I have watched and have GPT analyze these animes. Then, with whatever information that GPT could gather, have GPT recommend me an anime that is close to what I want.
"""

# 2. Code for GPT
top_10_animes = ['Suzumiya Haruhi no Yuuutsu',
                 'Saenai Heroine no Sodatekata Fine',
                 'Hyouka',
                 'Sakura-sou no Pet na Kanojo',
                 'Mondaiji-tachi ga Isekai kara Kuru Sou desu yo?',
                 'Heavy Object',
                 'Hanasaku Iroha',
                 'Fune wo Amu',
                 'No Game No Life: Zero',
                 'Wotaku ni Koi wa Muzukashii']

def get_anime_recommendation(list_of_animes):
  system_message = {
    "role" : "system",
    "content" : "Analyze each anime from the input and then answer the prompt"}

  direction = "Based on the 10 animes given, recommend another anime that would match the list."

  client = openai.OpenAI()
  response = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages= [
          system_message,
          {"role" : "user", "content" : direction + ", ".join(top_10_animes) + " - "}
      ],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["\n"]
  )

  time.sleep(1)

  answer = response.choices[0].message.content.strip()
  return answer


get_anime_recommendation(top_10_animes)

"""3. Write a short paragraph giving your qualitative analysis of how well GPT did for your task.

I would say that GPT did reasonably well with the recommendations that it gave.
After running the running the result 10 times, most answers from GPT gave either ReLIFE and Re:Zero which I have both watched and enjoy over many of the remaining animes that I've watched. However, the pitfall with what GPT returns is that the results only returns either ReLIFE or Re:Zero, so GPT seemingly only generates these two results. However, I think GPT's result is pretty satisfying especially because the anime ReLIFE is relatively less known comparatively to other animes with the same genre.

# Fine Tuning

In addition to zero-shot and few-shot learning, another way of getting large language models to do your tasks is via a process called "fine tuning".  In fine-tuning the model updates its parameters so that it performs well on many training examples.  The training examples are in the form of input prompts paired with gold standard completions.

Large language models are pre-trained to perform well on general tasks like text completion but not on the specific task that you might be interested in.  The models can be fine tuned to perform you task, starting with the model parameters that are good for the general setting, and then updating them to be good for your task.

We'll walk through how to fine-tune GPT for a task.

For this example, we will show you how to fine tune GPT to write biographies. From data in the info boxes in Wikipedia pages.  For instance, given this input

```
notable_type: scientist
name: Zulima Aban
gender: female
birth_date: 05 December 1905
birth_place: Valencia, Spain
death_date: 09 August 1983
death_place: Detroit, Michigan, U.S.
death_cause: Pulmonary embolism
occupation: Astronomer
fields: Astrophysics, Computer Science, Computer Graphics, Interface Design, Image Synthesis
known_for: The Search for Planet Nine
hometown: Detroit, Michigan, U.S.
nationality: Venezuelan
citizenship: Spanish, American
alma_mater: University of Valencia (B.Sc.), University of Madrid (Ph.D.)
thesis_title: The Formation of Planets by the Accretion of Small Particles
thesis_year: 1956
doctoral_advisor: Angela Carter
awards: Spanish Academy of Science, Spanish Academy of Engineering, German Aerospace Prize, IEEE Medal of Honor, IEEE John von Neumann Medal, IEEE Jack S. Kilby Signal Processing Medal, United Nations Space Pioneer Award, Wolf Prize in Physics
institutions: Oberlin College, University of Valencia, Instituto de Astrofísica de Andalucía (CSIC), University of Southern California, Space Telescope Science Institute (STScI)
notable_students: Ryan Walls
influences: Immanuel Kant, Albert Einstein, Kurt Gödel, Gottfried Leibniz, Richard Feynman, Werner Heisenberg, William Kingdon Clifford, Sir Arthur Eddington
influenced: Joseph Weinberg
mother: Ana Aban
father: Joaquín Aban
partner: Georgina Abbott
children: Robert, Peter, Sarah
```

The fine-tuned model will generate this output:

> Zulima Aban was a Venezuelan astronomer, who was born on 05 December 1905 in Valencia, Spain to Ana Aban and Joaquín Aban. Her career involved the fields of Astrophysics, Computer Science, Computer Graphics, Interface Design, Image Synthesis. Aban was known for The Search for Planet Nine. Aban went to University of Valencia (B.Sc.), University of Madrid (Ph.D.). Aban's thesis title was The Formation of Planets by the Accretion of Small Particles in 1956. Her doctoral advisor was Angela Carter. Aban received Spanish Academy of Science, Spanish Academy of Engineering, German Aerospace Prize, IEEE Medal of Honor, IEEE John von Neumann Medal, IEEE Jack S. Kilby Signal Processing Medal, United Nations Space Pioneer Award, Wolf Prize in Physics. Aban went to Oberlin College, University of Valencia, Instituto de Astrofísica de Andalucía (CSIC), University of Southern California, Space Telescope Science Institute (STScI). Her notable students were Ryan Walls. Aban was influenced by Immanuel Kant, Albert Einstein, Kurt Gödel, Gottfried Leibniz, Richard Feynman, Werner Heisenberg, William Kingdon Clifford, Sir Arthur Eddington and she infuenced Joseph Weinberg. Aban was married to Georgina Abbott and together had three children, Robert, Peter, Sarah. Aban died on 09 August 1983 in Detroit, Michigan, U.S due to Pulmonary embolism.

The dataset that we will use was created for the paper [SynthBio: A Case Study in Human-AI Collaborative Curation of Text Datasets](https://www.cis.upenn.edu/~ccb/publications/synthbio.pdf) by Ann Yuan, Daphne Ippolito, Vitaly Nikolaev, Chris Callison-Burch, Andy Coenen, and Sebastian Gehrmann. It was published in NeurIPS 2021.  The goal of the paper was to create a curated dataset for training large language models on synthetic data with the goal of avoiding the gender and geographic bias that is naturally present in Wikipedia due to cultural and historic reasons.

## Load the data
"""

!wget https://raw.githubusercontent.com/artificial-intelligence-class/artificial-intelligence-class.github.io/master/homeworks/large-LMs/SynthBio_train.json

# If you're running this locally on a Mac, you can use the following command instead.
# !curl -o SynthBio_train.json https://raw.githubusercontent.com/artificial-intelligence-class/artificial-intelligence-class.github.io/master/homeworks/large-LMs/SynthBio_train.json

# Load a file called 'SynthBio.json' which is a list of json objects.

import json
import random

def load_wiki_bio_data(filename='SynthBio_train.json', num_bios=100, randomized=True):
  with open(filename) as f:
    synth_bio_data = json.load(f)
  random.shuffle(synth_bio_data)
  bios = []
  for data in synth_bio_data:
    notable_type = data['notable_type']
    attributes = "notable_type: {notable_type} | {other_attributes}".format(
        notable_type = notable_type,
        other_attributes = data['serialized_attrs']
    )
    biography = data['biographies'][0]
    bios.append((attributes.replace(" | ", "\n"), biography))
  return bios[:min(num_bios, len(bios))]

wiki_bios = load_wiki_bio_data()
attributes, bio = wiki_bios[0]
print(attributes)
print('---')
bio

"""## Format Data for Fine-Tuning

Below, I show how to format data to fine-tune OpenAI.  The OpenAI API documentation has a [guide to fine-tuning models](https://platform.openai.com/docs/guides/fine-tuning/preparing-your-dataset) that you should read.   The basic format of fine-tuning data is a JSONL file (one JSON object per line) with an entry for `"messages"` that itself contains a list of `message` objects. Each `message` object consists of an entry for a `role` and `content`.

```
{"messages": [{"role": "system", "content": "Explanation for how LLM should behave."}, {"role": "user", "content": "User's prompt 1"}, {"role": "assistant", "content": "Expected response 1."}]}
{"messages": [{"role": "system", "content": "Explanation for how LLM should behave."}, {"role": "user", "content": "User's prompt 2"}, {"role": "assistant", "content": "Expected response 2."}]}
{"messages": [{"role": "system", "content": "Explanation for how LLM should behave."}, {"role": "user", "content": "User's prompt 3"}, {"role": "assistant", "content": "Expected response 3."}]}
...
```

In the code below, I'll extract a prompt that contains the `attributes` variable from the intent determination data, and I'll have the completion be the `biography` variable.
"""

import json

def create_wikibio_finetuning_data(wikibios, fine_tuning_filename):
  fine_tuning_data = []
  system_message = {"role" : "system", "content" : "You should generate a biography for a person based on the details provided."}

  for attributes, bio in wiki_bios:
    prompt = "{attributes}\n---\n".format(attributes=attributes)
    completion = "Biography: {bio}\n###".format(bio=bio)
    data = {"messages" : [system_message, {"role" : "user", "content" : prompt}, {"role" : "assistant", "content" : completion}]}
    fine_tuning_data.append(data)

  random.shuffle(fine_tuning_data)
  with open(fine_tuning_filename, 'w') as out:
    for data in fine_tuning_data:
        out.write(json.dumps(data))
        out.write('\n')


fine_tuning_filename='wikibio_finetuning_data.jsonl'
create_wikibio_finetuning_data(wiki_bios, fine_tuning_filename)

"""Next, we'll perform fine-tuning with this data using OpenAI."""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install --upgrade openai
# %pip install jsonlines
# %pip install wandb

"""Once you've got access to the OpenAI API, you can find your OpenAI API key [here](https://beta.openai.com/account/api-keys)."""

import os
import openai

from getpass import getpass
print('Enter OpenAI API key:')
openai.api_key = getpass()

os.environ['OPENAI_API_KEY']=openai.api_key

!head '{fine_tuning_filename}'

"""## Run the fine-tuning API

Next, we'll make the fine tuning call using the Python API. First, we must upload the training data to OpenAI. Once we do that, we can use the `id` of the uploaded data to perform the fine-tuning.
"""

client = openai.OpenAI()

client.files.create(
  file=open("wikibio_finetuning_data.jsonl", "rb"),
  purpose="fine-tune"
)

"""Make sure to change the string used for your `training_file` to the `id` that was returned as a result of the previous step.

**Do NOT repeatedly execute the following cell.**  It will cost you upwards of a dollar each time you run it. Run it once, and then move on to the next cell, where you can check its progress. The amount of time required for the fine-tune job to finish can be highly variable. Do not—again, **DO NOT**—repeatedly execute the following cell.
"""

client.fine_tuning.jobs.create(
  training_file="file-BfHYyHnzqoAhqdwza52u5qgX",
  model="gpt-3.5-turbo"
)

"""You should copy down the fine-tune's `id`.

You can list all of your fine-tune jobs and check their statuses using the following few examples.
"""

# List 10 fine-tuning jobs
client.fine_tuning.jobs.list(limit=10)

# Retrieve the state of a fine-tune
client.fine_tuning.jobs.retrieve("ftjob-f3xmrAFezAEFKqMI98fPs1j7")

# List up to 10 events from a fine-tuning job
client.fine_tuning.jobs.list_events(fine_tuning_job_id="ftjob-f3xmrAFezAEFKqMI98fPs1j7", limit=10)


# Cancel a job
# client.fine_tuning.jobs.cancel("my_job_id")

"""You can run your fine tuned model in the OpenAI Playground.  After the model is finished finetuning you'll find it in the Model dropdown menu (you might need to press reload in your browser for your fine-tuned model to appear).

## Call your fine-tuned model from the OpenAI API

Alternately, you can use your fine tuned model via the API by specifying it as the model.  Here's an example:
"""

def generate_bio(attributes, finetuned_model):
  client = openai.OpenAI()
  prompt = "{attributes}\n---\n".format(attributes=attributes)
  system_message = {"role" : "system", "content" : "You should generate a biography for a person based on the details provided."}
  response = client.chat.completions.create(
      model=finetuned_model,
      messages = [
          system_message,
          {"role" : "user", "content" : prompt}
      ],
      temperature=0.7,
      max_tokens=500,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      stop=["###"]
      )
  return response.choices[0].message.content.strip()

# Replace with your model's name
finetuned_model = "ft:gpt-3.5-turbo-0125:personal::AWTrTRIA"

attributes = """
notable_type: computer scienist
alma_mater: Stanford University (BS in Symbolic Systems), University of Edinburgh (PhD in Informatics)
birth_place: California
children: 2
gender: male
main_interests: Artificial Intelligence, Natural Language Processing
name: Chris Callison-Burch
nationality: American
notable_works: Moses: Open source toolkit for statistical machine translation, The Paraphrase Database (PPDB)
occupation: professor
courses_taught: AI, Crowdsourcing and NLP
enrollment_in_most_popular_course: 570 students
institution: University of Pennsylvania"""

biography = generate_bio(attributes, finetuned_model)
print(attributes)
print('---')
biography

"""## Analyze your model's output

Sometimes the model will add facts that are not present in the attributes.  For instance, one time it said
> He was a member of the research staff at IBM Research in Yorktown Heights.

which is not correct. Another time it said
> His most popular course was on AI, which had 570 students.

which is correct, but not specified in the attirbutes.

Try running your own fine-tuned model until it produces something that wasn't licensed by the attributes.

Save the good runs and the bad run below.
"""

generations_with_correct_facts = [
    """ Biography: Chris Callison-Burch is an American computer scientist. He was born in California and attended Stanford University, where he received a bachelor's degree in Symbolic Systems. He also attended the University of Edinburgh, where he received a PhD in Informatics. He is a professor at the University of Pennsylvania and his main interests are Artificial Intelligence, Natural Language Processing. He is a professor of computer and information science at the University of Pennsylvania. He teaches courses in AI, Crowdsourcing and NLP. He enrolled 570 students in his most popular course. He is a father of 2 children. His notable works are Moses: Open source toolkit for statistical machine translation, The Paraphrase Database (PPDB). """,
    """ Biography: Chris Callison-Burch is an Associate Professor of Computer and Information Science at the University of Pennsylvania. He received his B.S. in Symbolic Systems from Stanford University and his Ph.D. in Informatics from the University of Edinburgh. His main interests are Natural Language Processing and Artificial Intelligence. He has two children. He is a professor and his notable works are Moses: Open source toolkit for statistical machine translation, The Paraphrase Database (PPDB). He has enrolled 570 students in his course. He teaches AI, Crowdsourcing and NLP. """,
    ]

generation_with_incorrect_facts = """
Biography: Chris Callison-Burch is an American computer scientist. He is currently an associate professor in the Computer and Information Science department at the University of Pennsylvania. He is interested in artificial intelligence and natural language processing. He is best known for his work on Moses, an open source toolkit for statistical machine translation, and the Paraphrase Database (PPDB). He was born in California and has two children. He has a BS in Symbolic Systems from Stanford University and a PhD in Informatics from the University of Edinburgh. He has taught courses in AI, crowdsourcing, and NLP. He is currently enrolled in the most popular course at the University of Pennsylvania with 570 students.
"""

incorrect_facts = [
    """
      He is currently enrolled in the most popular course at the University of Pennsylvania with 570 students.
    """,
    ]

"""# Fine Tune a New Model

Now that you've seen an example of how to do fine-tuning with the OpenAI API, let's have you write code to fine-tune your own model.

For this model, I'd like you to do the reverse direction of what we just did.  Given a Wikipedia Biograph like this:

> Jill Tracy Jacobs Biden (born June 3, 1951) is an American educator and the current first lady of the United States as the wife of President Joe Biden. She was the second lady of the United States from 2009 to 2017. Since 2009, Biden has been a professor of English at Northern Virginia Community College.

> She has a bachelor's degree in English and a doctoral degree in education from the University of Delaware, as well as master's degrees in education and English from West Chester University and Villanova University. She taught English and reading in high schools for thirteen years and instructed adolescents with emotional disabilities at a psychiatric hospital. From 1993 to 2008, Biden was an English and writing instructor at Delaware Technical & Community College. Biden is thought to be the first wife of a vice president or president to hold a paying job during her husband's tenure.

> Born in Hammonton, New Jersey, she grew up in Willow Grove, Pennsylvania. She married Joe Biden in 1977, becoming stepmother to Beau and Hunter, his two sons from his first marriage. Biden and her husband also have a daughter together, Ashley Biden, born in 1981. She is the founder of the Biden Breast Health Initiative non-profit organization, co-founder of the Book Buddies program, co-founder of the Biden Foundation, is active in Delaware Boots on the Ground, and with Michelle Obama is co-founder of Joining Forces. She has published a memoir and two children's books.

Your model should output something like this:
```
notable_type: First Lady of the United States
name: Jill Biden
gender: female
nationality: American
birth_date: 03 June 1951
birth_place: Hammonton, New Jersey
alma_mater: University of Delaware
occupation: professor of English at Northern Virginia Community College
notable_works: children's books and memoir
main_interests: education, literacy, women's health
partner: Joe Biden
children: Ashley Biden, Beau Biden (stepson), Hunter Biden (stepson)
```

"""

import json

def create_wikibio_parser_finetuning_data(wikibios, fine_tuning_filename):
  finetune_data = []

  for bio in wikibios:
      attributes, biography = bio

      finetune_data.append({
          "messages": [
              {"role": "system", "content": "You are a tasked to extract key attributes from the given biographies."},
              {"role": "user", "content": biography},
              {"role": "assistant", "content": attributes}
          ]
      })

  with open(fine_tuning_filename, 'w') as outfile:
      for entry in finetune_data:
          json.dump(entry, outfile)
          outfile.write('\n')

fine_tuning_filename='wikibio_parser_finetuning_data.jsonl'
create_wikibio_parser_finetuning_data(wiki_bios, fine_tuning_filename)

# Upload the file to OpenAI's API (only do this when you're confident your data looks right.)
client.files.create(
  file=open("wikibio_parser_finetuning_data.jsonl", "rb"),
  purpose="fine-tune"
)

# Create a fine-tune job. Careful! ($$$)
client.fine_tuning.jobs.create(
  training_file="file-QNdHych4DYqf3giMaCk4SA",
  model="gpt-3.5-turbo"
)

# List 10 fine-tuning jobs
client.fine_tuning.jobs.list(limit=10)

# Retrieve the state of a fine-tune
client.fine_tuning.jobs.retrieve("ftjob-kaaFVtYSi2pluXE1SA7shGU8")

# List up to 10 events from a fine-tuning job
# client.fine_tuning.jobs.list_events(fine_tuning_job_id="ftjob-soJUil8lcql2p75g3MOhlFKc", limit=10)

def parse_bio(biography, finetuned_bio_parser_model):
  client = openai.OpenAI()
  response = openai.chat.completions.create(
      model=finetuned_bio_parser_model,
      messages=[
          {"role": "system", "content": "Read through the biography and extract relevant key features from the biography text."},
          {"role": "user", "content": biography}
      ],
      max_tokens=500,
      temperature=0.7
  )

  return response.choices[0].message.content


finetuned_bio_parser_model="ft:gpt-3.5-turbo-0125:personal::AY8T0PX7"

"""## Test your parser

Next we will test your parser.  This will involve calling your `parse_bio` function about 250 times, so be sure that you've got it properly debugged and working before running this code.
"""

!wget https://raw.githubusercontent.com/artificial-intelligence-class/artificial-intelligence-class.github.io/master/homeworks/large-LMs/SynthBio_test.json

import json

def load_wiki_bio_test_set(filename='SynthBio_test.json', max_test_items=10, randomized=True):
  """
  Loads our wikibio test set, and returns a list of tuples
  biographies (text), attributes (dictionaires)
  """
  with open(filename) as f:
    synth_bio_data = json.load(f)
  bios = []
  for data in synth_bio_data:
    notable_type = data['notable_type']
    attributes = data['attrs']
    attributes['notable_type'] = notable_type
    biography = data['biographies'][0]
    bios.append((biography, attributes))
  return bios[:min(max_test_items, len(bios))]

def convert_to_dict(predcited_attributes_txt):
  """
  Converts predicted attributes from text format into a dictionary.
  """
  predicted_attributes = {}
  for line in predcited_attributes_txt.split('\n'):
    try:
      attribute, value = line.split(':')
      predicted_attributes[attribute.strip()] = value.strip()
    except ValueError:
      continue
  return predicted_attributes

bio = """
Biography: Chris Callison-Burch is an American computer scientist and professor. He was born in California and attended Stanford University (BS in Symbolic Systems), University of Edinburgh (PhD in Informatics). He is a professor at the University of Pennsylvania. He is best known for his work in Artificial Intelligence and Natural Language Processing. He created the Moses: Open source toolkit for statistical machine translation, The Paraphrase Database (PPDB). He taught courses in AI, Crowdsourcing and NLP. He had 570 students enrolled in his most popular course.
"""
attr = parse_bio(bio, finetuned_bio_parser_model)
print(bio)
print("---")
print(attr)
print("---")

predicted_attributes = {}
print(attr.split('\n'))

"""Helper function for computing precision, recall and f-score."""

from collections import Counter

def update_counts(gold_attributes, predicted_attributes, true_positives, false_positives, false_negatives, all_attributes):
  # Compute true positives and false negatives
  for attribute in gold_attributes:
    all_attributes[attribute] += 1
    if attribute in predicted_attributes:
      # gold attribute exists in predicted attributes
      # some attributes have multiple values
      predicted_values = predicted_attributes[attribute].split(',')
      gold_values = gold_attributes[attribute].split(',')
      for value in gold_values:
        if value.strip() in predicted_values:
          # gold attribute exists in predicted attributes and gold value exists in predicted values
          true_positives[attribute] += 1
        else:
          # gold attribute exists in predicted attributes but gold value does not exist in predicted values
          false_negatives[attribute] += 1
    else:
      # gold attribute does not exist in predicted attributes
      false_negatives[attribute] += 1

  # Compute false positives
  for attribute in predicted_attributes:
    if attribute not in gold_attributes:
      # predicted attribute does not exist in gold attributes
      all_attributes[attribute] += 1
      false_positives[attribute] += 1
    else:
      # predicted attribute exists in gold attributes
      # some attributes have multiple values
      gold_values = gold_attributes[attribute].split(',')
      predicted_values = predicted_attributes[attribute].split(',')
      for value in predicted_values:
        if value.strip() not in gold_values:
          # predicted attribute exists in gold attributes but predicted value does not exist in gold values
          false_positives[attribute] += 1

def evaluate_on_test_set(finetuned_bio_parser_model, wiki_bio_test, threshold_count = 5):
  """
  Computer the precision, recall and f-score for each of the attributes
  that appears more than the treshold count
  """
  true_positives = Counter()
  false_positives = Counter()
  false_negatives = Counter()
  all_attributes = Counter()

  for bio, gold_attributes in wiki_bio_test:
    predicted_attributes = convert_to_dict(parse_bio(bio, finetuned_bio_parser_model))
    update_counts(gold_attributes, predicted_attributes, true_positives, false_positives, false_negatives, all_attributes)

  average_precision = 0
  average_recall = 0
  total = 0

  for attribute in all_attributes:
    if all_attributes[attribute] < threshold_count:
      continue
    print(attribute.upper())
    try:
      precision = true_positives[attribute] / (true_positives[attribute] + false_positives[attribute])
    except:
      precision = 0.0
    try:
      recall = true_positives[attribute] / (true_positives[attribute] + false_negatives[attribute])
    except:
      recall = 0.0
    print("precision:", precision)
    print("recall:", recall)
    print("f-score:", (precision+recall)/2)
    print('---')
    average_precision += precision
    average_recall += recall
    total += 1

  print("AVERAGE")
  average_precision = average_precision/total
  average_recall = average_recall/total
  print("precision:", average_precision)
  print("recall:", average_recall)
  print("f-score:", (average_precision+average_recall)/2)
  print('---')

"""If you would like to evaluate on the full test set, there are 237 test items.  You can set `max_test_items=237`.  Doing so will call your `parse_bio` function about 237 times, so be sure that you've got it properly debugged and working before running this code.

# **Important: Grading Criteria**

For a thorough evaluation of the model, max_test_items has to be set to a **minimum of 50**. To receive full credit, you have to submit a previously run notebook with all outputs included. Full credit will be awarded if **all three metrics—average precision, average recall, and average f-score—exceed 0.4 (40%) on at least 50 examples**.
"""

testset_filename = 'SynthBio_test.json'
max_test_items = 50  # set to 10 for initial testing; for final testing and submission, choose a value between 50 and 237
wiki_bio_test = load_wiki_bio_test_set(testset_filename, max_test_items)
evaluate_on_test_set(finetuned_bio_parser_model, wiki_bio_test, threshold_count=5)

"""How well did your model perform?"""

# TODO - fill in these values
average_precision = 0.45512788367185397
average_recall = 0.4441332374143681
average_fscore = 0.449630560543111

# What attributes had the highest F-scores
best_attributes = {
    "GENDER" : 0.8983333333333333,
    "BIRTH_DATE" : 0.88,
    "NOTABLE_TYPE" : 0.94,
}

# What attributes had the lowest F-scores
worst_attributes = {
    "FIELDS" : 0.08125,
    "NOTABLE_ASCENTS" : 0.10555555555555556,
    "OCCUPATION" : 0.13392857142857142,
}

# What could you do the perform the model's performance?
potential_improvements = """
Some of the worse performing attributes are those that could be inconsistent from datapoint to datapoint so
one way of improving the performance is to make sure when labeling the data, they are consistent in that if
there are missing entries, label it as N/A or let it be known that a valid entry of N/A is acceptable for
unknown informations.
"""

"""# Feedback questions"""

# How many hours did you spend on this assignment? Just an approximation is fine.
num_hours_spent = 6

# What did you think?  This was the first time we tried this assignment
# so you're feedback is valable.
feedback = """
It was neat.
"""